#!/usr/bin/env python
import sys
import os
import subprocess
import time

sys.path.append('/scripts/')

import createvhosts
import xmlapi

# mod_rpaf include is now going to the pre_main_global.conf
def findrpaf(ioru):
        f=open('/usr/local/apache/conf/includes/pre_main_global.conf', 'r')
        fl = f.readlines()
        f.close
        include="Include \"/usr/local/apache/conf/includes/rpaf.conf\"\n"
        if include in fl:
                if ioru == "install":
                        pass
                if ioru == "uninstall":
                        fl.remove(include)
                        f=open('/usr/local/apache/conf/includes/pre_main_global.conf', 'w')
                        f.writelines(fl)
                        f.close
        else:
                if ioru == "install":
                        fl.insert(0, include)
                        f=open('/usr/local/apache/conf/includes/pre_main_global.conf', 'w')
                        f.writelines(fl)
                        f.close
                if ioru == "uninstall":
                        pass


ipliststring = createvhosts.getipliststring()

rpafinclude = """cat >> "/usr/local/apache/conf/includes/rpaf.conf" <<EOF
LoadModule rpaf_module modules/mod_rpaf-2.0.so
#Mod_rpaf settings
RPAFenable On
RPAFproxy_ips 127.0.0.1 %s
RPAFsethostname On
EOF""" % (ipliststring)

proc = subprocess.Popen(rpafinclude, shell=True)
output = proc.communicate()

ioru=sys.argv[1]
rpafinstalluninstall=findrpaf(ioru)

proc = subprocess.Popen("/usr/local/cpanel/bin/apache_conf_distiller --update > /dev/null 2>&1", shell=True)
output = proc.communicate()
time.sleep(5)

## Removed nginx logrotate script
print "Adjusting cPanel/Apache ports to :8081"  

proc = subprocess.Popen("sed -i 's/localhost/localhost:8081/g' /etc/init.d/httpd", shell=True)
output = proc.communicate()

proc = subprocess.Popen("sed -i 's/localhost/localhost:8081/g' /usr/sbin/httpd", shell=True)
output = proc.communicate()
proc = subprocess.Popen("sed -i 's/apache_port=0.0.0.0:80$/apache_port=0.0.0.0:8081/' /var/cpanel/cpanel.config", shell=True)
output = proc.communicate()

print "Updating cPanel Tweak Setting, please hold to yer pants"
subprocess.Popen("/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings > /dev/null 2>&1", shell=True)

time.sleep(10)
print " Installation Complete -- run /etc/init.d/nginx restart to start nginx"
