#!/usr/bin/env python
import sys
import os
import subprocess
import time

sys.path.append('/scripts/')

import createvhosts
import xmlapi


def findrpaf(ioru):
        f=open('/usr/local/apache/conf/httpd.conf', 'r')
        fl = f.readlines()
        f.close
        include="Include \"/usr/local/apache/conf/includes/rpaf.conf\"\n"
        if include in fl:
                if ioru == "install":
                        pass
                if ioru == "uninstall":
                        fl.remove(include)
                        f=open('/usr/local/apache/conf/httpd.conf', 'w')
                        f.writelines(fl)
                        f.close
        else:
                if ioru == "install":
                        fl.insert(29, include)
                        f=open('/usr/local/apache/conf/httpd.conf', 'w')
                        f.writelines(fl)
                        f.close
                if ioru == "uninstall":
                        pass


ipliststring = createvhosts.getipliststring()

rpafinclude = """cat >> "/usr/local/apache/conf/includes/rpaf.conf" <<EOF
LoadModule rpaf_module modules/mod_rpaf-2.0.so
#Mod_rpaf settings
RPAFenable On
RPAFproxy_ips 127.0.0.1 %s
RPAFsethostname On
EOF""" % (ipliststring)

proc = subprocess.Popen(rpafinclude, shell=True)
output = proc.communicate()

ioru=sys.argv[1]
rpafinstalluninstall=findrpaf(ioru)

proc = subprocess.Popen("/usr/local/cpanel/bin/apache_conf_distiller --update > /dev/null 2>&1", shell=True)
output = proc.communicate()
time.sleep(5)

#rotatescript = """cat >> "/etc/logrotate.d/nginx" <<EOF
#
#/var/log/nginx/*log {
#    missingok
#    notifempty
#    sharedscripts
#    postrotate
#        /bin/kill -HUP \`cat /var/run/nginx.pid 2>/dev/null\` 2> /dev/null || true
#    endscript
#}
#EOF""" 

#proc = subprocess.Popen(rotatescript, shell=True)
#output = proc.communicate()

#ncheckservd = "service[nginx]=x,x,x,service nginx restart,nginx,root"

#nchkservdf = open('/etc/chkserv.d/nginx', 'w')

#nchkservdf.write(ncheckservd)

#nchkservdf.close()


print " gettin there "  


proc = subprocess.Popen("sed -i 's/localhost/localhost:8081/g' /etc/init.d/httpd", shell=True)
output = proc.communicate()

proc = subprocess.Popen("sed -i 's/localhost/localhost:8081/g' /usr/sbin/httpd", shell=True)
output = proc.communicate()


proc = subprocess.Popen("sed -i 's/apache_port=0.0.0.0:80$/apache_port=0.0.0.0:8081/' /var/cpanel/cpanel.config", shell=True)
output = proc.communicate()
subprocess.Popen("/usr/local/cpanel/whostmgr/bin/whostmgr2 --updatetweaksettings > /dev/null 2>&1", shell=True)

time.sleep(10)
#proc = subprocess.Popen("/etc/init.d/nginx restart > /dev/null 2>&1", shell=True)
#output = proc.communicate()
print " Installation Complete -- run /etc/init.d/nginx restart to start nginx"
